### ISSUE TITLE
PHP Fatal Error·Interface 'Psr\Http\Message\UriInterface' not found

### ISSUE THREAD

**Issue by audvin** [Giuseppe-Mazzapica/Cortex#10]
Hi, 

I'm having a curious bug here. Cortex and my code works great in my staging environment, but as soon as I pull to production I get this error:

`PHP Fatal Error·Interface 'Psr\Http\Message\UriInterface' not found`

<img width="698" alt="screen shot 2016-03-09 at 4 30 41 pm" src="https://cloud.githubusercontent.com/assets/1017880/13655508/b4de77cc-e614-11e5-9a9a-fbe68019f894.png">

I've been unable to find a solution. Any tips?

I'm using `"brain/cortex": "~1.0.0"`

**Comment by gmazzap** [comment]
Hi, you have to use `0.1.*` version. `1.*` has breaking changes.
