### ISSUE TITLE
Defaults and host information in route groups

### ISSUE THREAD

**Issue by Solinx** [Giuseppe-Mazzapica/Cortex#2]
Hello Giuseppe,

As told in the prior issue report there were other minor issues we've uncovered. Both other issues concern the grouping functionality.

1. Setting a host in a route group does not appear to have any effect.
2. Setting defaults for parameters that do not appear in the url do not get applied.

Because there are obvious workarounds we have not taken the time to look into the reason for these issues. It would be nice to have a fix for this, but it's not like we can't do without this functionality.

Cheers,
Wouter van Dam

**Comment by Giuseppe-Mazzapica** [comment]
Closing to keep issue tracker clean...
