### ISSUE TITLE
Abandoned packages and Parse error | PHP 8.0.11

### ISSUE THREAD

**Issue by andriilive** [Giuseppe-Mazzapica/Cortex#29]
Package brain/amygdala is abandoned, you should avoid using it. No replacement was suggested.
Package brain/brain is abandoned, you should avoid using it. No replacement was suggested.
Package brain/striatum is abandoned, you should avoid using it. No replacement was suggested.
Package brain/support is abandoned, you should avoid using it. No replacement was suggested.
Package twig/cache-extension is abandoned, you should avoid using it. Use twig/cache-extra instead.

( ! ) Parse error: syntax error, unexpected token "\" in /Users/andy/Documents/associationweb/web/app/themes/asweb/vendor/brain/support/src/Facade.php on line 34

**Comment by gmazzap** [comment]
You're using "master" branch which is long abandoned.

You should use [`refactoring-fastroute`](https://github.com/Brain-WP/Cortex) branch (which is the default), or even better one of the [releases](https://github.com/Brain-WP/Cortex/releases).
