### ISSUE TITLE
WPML and Cortex

### ISSUE THREAD

**Issue by meszarosrob** [Giuseppe-Mazzapica/Cortex#3]
Hello Guiseppe,

have you tried using Cortex's routing capabilities with a site that uses WPML for making it multilingual? I guess it won't really work out of the box. Do you think with route groups and and callback it would be manageable? Or in general how would you aproach a site with multiple languages? Multisites?

**Comment by Giuseppe-Mazzapica** [comment]
Hi @meszarosrob  once I get no response in a long time, I'm going to close this issue. If you still have some issues feel free to re-open it. Thanks.
