### ISSUE TITLE
Issue with wordpress v6

### ISSUE THREAD

**Issue by bahreynipour** [Giuseppe-Mazzapica/Cortex#33]
Hi, 
Thank you for your great work. I'm using cortex from past year. But recently there is an issue with wordpress v6.
Cortex routes not working, Would you please help?

**Comment by Mte90** [comment]
any plans for an update?

**Comment by gmazzap** [comment]
See https://github.com/Brain-WP/Cortex/releases/tag/1.0.0-alpha.9
