### ISSUE TITLE
Cortex is not booted

### ISSUE THREAD

**Issue by kapooostin** [Giuseppe-Mazzapica/Cortex#7]
The hook `brain_loaded` is never fired, if I use `init` I get Domain Exception. It is thrown when a Brain module was not booted if I understand correctly.

I have `Brain\Cortex::boot()` in my theme's `functions.php` file. Is it too late to boot it?

**Comment by Giuseppe-Mazzapica** [comment]
Are you using a Composer full-stack installation? (the whole website installed via Composer, including WP core)

**Comment by kapooostin** [comment]
Yes, I use [Bedrock](https://roots.io/bedrock/).

**Comment by Giuseppe-Mazzapica** [comment]
That's a know issue with Cortex and full stack Composer installs. It is planned to be fixed, but not found the time yet.

That's one of the reasons no stable branch of Cortex has been released.

More details and a solution here https://github.com/Giuseppe-Mazzapica/Cortex/issues/4#issuecomment-65920146

**Comment by kapooostin** [comment]
Should I close this issue or you'll need it as a reminder?

**Comment by Giuseppe-Mazzapica** [comment]
Let's keep it open for now, with the hope that this will make the release of `v1.0` faster ;)
