### ISSUE TITLE
WP_Error( 'too-early-for-url-generator' ) maybe is thrown too late

### ISSUE THREAD

**Issue by kapooostin** [Giuseppe-Mazzapica/Cortex#8]
I get this error while generating my view. But if I use ```$brain->get( 'symfony.generator' )->generate( $route_id, $args )``, it works just fine.

**Comment by Giuseppe-Mazzapica** [comment]
Sorry for this very long delay. I had no very defined idea on what to do with this package.

Now I have, and changes will come..

Thanks for reporting, by the way.

**Comment by kapooostin** [comment]
Oh, that's great! Looking forward to it.
